### ISSUE TITLE
Tautology in boolean logic

### ISSUE THREAD

**Issue by TheAlgorythm** [nsdigirolamo/rust-cards#2]
https://github.com/nsdigirolamo/rust-cards/blob/f8a81cb29a51e08429201ad17205d78d53ae7302/src/main.rs#L13

Everything smaller than 1 is also smaller than 11.

I would prefer ranges as the intent is clearer (like https://zschoen.dev/blog/what-ive-learned-from-advent-of-code-2020/#0x02)
and use `match`:

```Rust
match card.rank {
    ..1 => {},
    2..=11 => {},
    12.. => {},
}
```

Also here:
https://github.com/nsdigirolamo/rust-cards/blob/main/src/main.rs#L61-L70

**Comment by nsdigirolamo** [comment]
I replaced the if statements with match and ranges. Thank you!
